config/routes.rb
Rails.application.routes.draw do
  get 'bookings/book'
  post 'bookings/createBooking'
  get 'bookings/createBooking'
  get 'main/index'
  resources :slots
  get 'errors/accesserror'
  get 'doctors/new'
  get 'doctors/createslot'
  get 'home/index'
  get 'home/mybookings'
  post 'home/index'
  root 'main#index'
  get 'slots/index'
  get 'bookings/index'
  get 'doctors/show'
  get 'doctors/index'
  get 'doctors/create'
  post 'doctors/create'
  resources :hospitals
  devise_for :users, :controllers => {registrations: 'users/registrations',sessions: 'users/sessions'}

  devise_scope :user do
    get 'users/sign_out' => 'users/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :doctor
  belongs_to :hospital
  def self.slotRollBack
    raise ActiveRecord::Rollback
  end
  def self.setSlot slot
    flag = 0
    @total_slot_time = slot.time_out.to_time - slot.time_in.to_time
    @no_of_intervals = (@total_slot_time/15.minutes).round
    @temp=slot.time_in.to_time
    (@no_of_intervals).times do |s|
      @interval = Interval.new
      @interval.slot_id = slot.id
      if(s == 0)
        @time = @temp.to_time
      else
        @time = @temp.to_time + 15.minutes
      end
      @interval.timeslot = @time.strftime("%I:%M%p")
      @interval.is_available = true
      @temp=@interval.timeslot
        if @interval.save
           flag = flag+1
        else
           flag = 0
        end
    end
    if flag < @no_of_intervals
      return false
    else
      return true
    end
  end

  def self.populateDates
    @dates =[Date.today,Date.today+1,Date.today+2,Date.today+3,Date.today+4]
    return @dates
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy]
  before_action :check_role, except: [:index]
  skip_before_action :verify_authenticity_token
  # GET /slots
  # GET /slots.json
  def index
   @doc_id = Doctor.where(:user_id => current_user.id)
   @slots = Slot.where(:doctor_id => @doc_id.ids.first)
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
  end

  # GET /slots/new
  def new
    @slot = Slot.new
    @hospitals = Hospital.all.collect{|i| [i.name , i.id]}
    @dates = Slot.populateDates
  end

  # GET /slots/1/edit
  def edit
    @hospitals = Hospital.all.collect{|i| [i.name , i.id]}
    @dates = Slot.populateDates    
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = Slot.new(slot_params)
    @doc_id = Doctor.where(:user_id => current_user.id)
    @hospitals = Hospital.all.collect{|i| [i.name , i.id]}
    @slot.doctor_id = @doc_id.ids.first
    @dates = Slot.populateDates
    respond_to do |format|
      if @slot.save
        @isSetSlot = Slot.setSlot @slot
        if(@isSetSlot == true)
          format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
          format.json { render :show, status: :created, location: @slot }
        else
          Slot.slotRollBack
          format.html { render :new }
          format.json { render json: @slot.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url, notice: 'Slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_params
      params.require(:slot).permit( :hospital_id, :date, :time_in, :time_out)
    end
    def check_role
      if current_user.role =="doctor"
        return true
      else
        redirect_to errors_accesserror_path
      end
   end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_with(model: slot, local: true) do |form| %>
  <% if slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <table>


 <tr>
  <div class="field">
  <td><%= form.label :hospital_id %></td>
  <td><%= form.select :hospital_id, @hospitals, id: :slot_hospital_id %></td>
  </div>
  </tr>

  <tr>

  <div class="field">
  <td><%= form.label :date %></td>
  <td><%= form.select :date, @dates, id: :slot_date %></td>
  </div>
  </tr>
  <tr>

  <div class="field" >
  <td> <%= form.label :time_in %></td>
  <td><%= form.text_field :time_in, id: :slot_time_in %></td>
  </div>
  </tr>
  <tr>

  <div class="form-group">
  <td><%= form.label :time_out %></td>
  <td><%= form.text_field :time_out, id: :slot_time_out %></td>
  </div>
  </tr>
  <tr>
  <div class="actions">
  <td><%= form.submit %></td>
  </div>
  </tr>
<% end %>
</table>

app/views/slots/edit.html.erb
<h1>Editing Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<p id="notice"><%= notice %></p>
<h1 align="center">Slots</h1>

<div class="container-fluid">
<html>
<style>
    th{
        width:8%
        border-color:black;
        
    }

    .table th {
      text-align: center;
      border-color:black;
  }
  
  .table {
    border-color:black;
    border-radius: 10px;
    width: 50%;
    margin: 0px auto;
    float: none;
  }
  .container-fluid {
   
}
</style>
<body>

<table  class="table table-bordered able-hover text-centered  table-inverse ">
<thead class="thead-inverse">



    <tr>
      <th>User</th>
      <th>Hospital</th>
      <th>Date</th>
      <th>Time in</th>
      <th>Time out</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <td><%= slot.doctor.user.name %></td>
        <td><%= slot.hospital.name %></td>
        <td><%= slot.date %></td>
        <td><%= slot.time_in %></td>
        <td><%= slot.time_out %></td>
        <td><%= link_to 'Show', slot %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
        <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p align="center"><%= link_to 'New Slot', new_slot_path ,class:'btn btn-success'%></p>
</div>

app/views/slots/new.html.erb
<html>
<style>
body{
  background-repeat: no-repeat;
  background-size: cover;
}

h1 {
    text-shadow: 4px 2px #FF0000;
}

</style>
<body background="/assets/l.jpg">

<div style="padding-left:100px;padding-top:100px">
<div class="panel panel-default col-sm-7" >
  <div class="panel-heading" style="padding-left:140px"><h1 style="color: #4B0082;">New Slot</h1><br/></div>
  <div class="panel-body" style="padding-left:140px;background-color: #FFE4C4">


<%= render 'form', slot: @slot %>

<%= link_to 'Back', slots_path ,class:'btn btn-primary'%>
</div>
</div>
</body>
</html>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @slot.doctor.user.name %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @slot.hospital.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @slot.date %>
</p>

<p>
  <strong>Time in:</strong>
  <%= @slot.time_in %>
</p>

<p>
  <strong>Time out:</strong>
  <%= @slot.time_out %>
</p>

<p>
  <strong>No of patients:</strong>
  <%= @slot.no_of_patients %>
</p>

<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>