config/routes.rb
Rails.application.routes.draw do
  get 'bookings/book'
  post 'bookings/createBooking'
  get 'bookings/createBooking'
  get 'main/index'
  resources :slots
  get 'errors/accesserror'
  get 'doctors/new'
  get 'doctors/createslot'
  get 'home/index'
  get 'home/mybookings'
  post 'home/index'
  root 'main#index'
  get 'slots/index'
  get 'bookings/index'
  get 'doctors/show'
  get 'doctors/index'
  get 'doctors/create'
  post 'doctors/create'
  resources :hospitals
  devise_for :users, :controllers => {registrations: 'users/registrations',sessions: 'users/sessions'}

  devise_scope :user do
    get 'users/sign_out' => 'users/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hospital.rb
class Hospital < ApplicationRecord
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]
  before_action :check_role
  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:name, :place, :pin, :phone)
    end
    def check_role
       if current_user.role =="admin"
         return true
       else
         redirect_to errors_accesserror_path
       end
    end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<%= form_with(model: hospital, local: true) do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <html>
  <style>
  body {
    background-color: lightblue;
  }
  
     
      th{
          width:10%
         
          
      }
  
      .table th {
        text-align: center;
        
    }
    
    .table {
    
      background-color:#f5f5f5;
      border-radius: 10px;
      width: 50%;
      margin: 0px auto;
      float: none;
      margin-top:5%;
      margin-left:30%;
      margin-bottom:5;
    }
    
  </style>

<body>
<table class="table text-centered table-bordered">
<thead class="thead-inverse">
<tr>
  <div class="field">
    <td><%= form.label :name %></td>
    <td><%= form.text_field :name, id: :hospital_name %></td>
  </div>
</tr>
<tr>
  <div class="field">
  <td><%= form.label :place %></td>
  <td><%= form.text_field :place, id: :hospital_place %></td>
  </div>
  </tr><tr>

  <div class="field">
  <td> <%= form.label :pin %></td>
  <td><%= form.text_field :pin, id: :hospital_pin %></td>
  </div>
  </tr><tr>

  <div class="field">
  <td><%= form.label :phone %></td>
  <td><%= form.text_field :phone, id: :hospital_phone %></td>
  </div>
  </tr><tr>

  <div class="actions">
  <td><%= form.submit %> </td>
  </div>
  <tr>
<% end %>
</table></body>
</html>

app/views/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<html>
<style>

body {
  background-color: lightblue;
}
    th{
        width:10%
       
        
    }

    .table th {
      text-align: center;
      
  }
  
  .table {
  
    background-color:#f5f5f5;
    border-radius: 10px;
    width: 50%;
    margin: 0px auto;
    float: none;
    margin-top:5%;
    margin-left:30%;
    margin-bottom:2%;
  }
  
</style>
<body>

<h1 align="center">HOSPITALS</h1>

<table class="table text-centered table-bordered">
<thead class="thead-inverse">
<tr>
<th>Name</th>
<th>Place</th>
<th>Pin</th>
<th>Phone</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @hospitals.each do |hospital| %>
  <tr>
    <td><%= hospital.name %></td>
    <td><%= hospital.place %></td>
    <td><%= hospital.pin %></td>
    <td><%= hospital.phone %></td>
    <td><%= link_to 'Show', hospital %></td>
    <td><%= link_to 'Edit', edit_hospital_path(hospital) %></td>
    <td><%= link_to 'Destroy', hospital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>
</body>
</html>

<p align="center"><%= link_to 'New Hospital', new_hospital_path ,class:"btn btn-primary" %></p>

app/views/hospitals/new.html.erb
<h1 align="center">New Hospital</h1>
<%= render 'form', hospital: @hospital %>
<h4 align="center" ><%= link_to 'Back', hospitals_path  ,class:"btn btn-primary"%></h4>

app/views/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hospital.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @hospital.place %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @hospital.pin %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @hospital.phone %>
</p>

<%= link_to 'Edit', edit_hospital_path(@hospital) %> |
<%= link_to 'Back', hospitals_path %>