config/routes.rb
Rails.application.routes.draw do
  get 'bookings/book'
  post 'bookings/createBooking'
  get 'bookings/createBooking'
  get 'main/index'
  resources :slots
  get 'errors/accesserror'
  get 'doctors/new'
  get 'doctors/createslot'
  get 'home/index'
  get 'home/mybookings'
  post 'home/index'
  root 'main#index'
  get 'slots/index'
  get 'bookings/index'
  get 'doctors/show'
  get 'doctors/index'
  get 'doctors/create'
  post 'doctors/create'
  resources :hospitals
  devise_for :users, :controllers => {registrations: 'users/registrations',sessions: 'users/sessions'}

  devise_scope :user do
    get 'users/sign_out' => 'users/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :user
  has_many :slots
  has_many :hospitals, through: :slots
  delegate :name,:phone, to: :user, prefix: "user"
  
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_role
  def index
    doc_id=Doctor.where(:user_id=>current_user.id)
    @bookings = Booking.where(:doctor_id => doc_id.first.id)
  end
  def show
    @booking = Booking.find(params[:id])
  end
  def create
    @booking = Booking.find(params[:bookingId])
    if  @booking.update_attributes(booking_params)
      redirect_to doctors_index_path
    else
      flash[:error] = "Error in Updating"
      redirect_to root_path
    end
  end
  private
  def booking_params
    params.require(:booking).permit(:observation , :status)
  end
  def check_role
    if current_user.role =="doctor"
      return true
    else
      redirect_to errors_accesserror_path
    end
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/index.html.erb
<%= render 'main/bookings' %><br>
<p align="center"><%= link_to 'newSlot', new_slot_path  ,class:'btn btn-primary'%></p>

app/views/doctors/show.html.erb
<%= @booking.id %>
<%= @booking.user.name %>
<%= @booking.hospital.name %>
<%= @booking.doctor.user.name %>
<%= @booking.illness %>
<%= @booking.symptoms %>
<%= form_for :booking , url: doctors_create_path do |f| %>
    Observation: <%= f.text_area :observation %><br />
    Status: <%= f.check_box :status %>
    <input type="hidden" value = <%= @booking.id %> name="bookingId"/>
    <%= f.submit %>
  <% end %>
  