config/routes.rb
Rails.application.routes.draw do
  get 'bookings/book'
  post 'bookings/createBooking'
  get 'bookings/createBooking'
  get 'main/index'
  resources :slots
  get 'errors/accesserror'
  get 'doctors/new'
  get 'doctors/createslot'
  get 'home/index'
  get 'home/mybookings'
  post 'home/index'
  root 'main#index'
  get 'slots/index'
  get 'bookings/index'
  get 'doctors/show'
  get 'doctors/index'
  get 'doctors/create'
  post 'doctors/create'
  resources :hospitals
  devise_for :users, :controllers => {registrations: 'users/registrations',sessions: 'users/sessions'}

  devise_scope :user do
    get 'users/sign_out' => 'users/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HMS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body class="container-fluid">
  <nav class="navbar navbar-inverse">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">HMS</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
      
            <li class="active"><a href= <%= root_path %> >Home</a></li>
            <% if current_user.role == "doctor" %>
              <li><a href= <%= doctors_index_path %> >Bookings</a></li>
              <li><a href= <%= new_slot_path %> >NewSlot</a></li>
              <li><a href= <%= slots_path %> >My Slots</a></li>
            <% end %>
            <% if current_user.role == "patient" %>
              <li><a href= <%= home_mybookings_path %> >My Bookings</a></li>
              <li><a href= <%= home_index_path %> >Search</a></li>
            <% end %>
            <% if current_user.role == "admin" %>
              <li><a href= <%= new_hospital_path %> >New Hospital</a></li>
              <li><a href= <%= hospitals_path %> >All Hospitals</a></li>
            <% end %>
            <li ><a href= <%= root_path %> >About Us</a></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      
    
    
        <li><a href="/users/sign_out"><span class="glyphicon glyphicon-log-out">&nbspLogout</a></li>
      </ul>
    </div>
  </nav>
    
    <%= yield %>
  </body>
</html>